name: notebox
description: A Flutter netease cloud music client.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.3
  window_manager: ^0.2.1
  dart_vlc: ^0.1.9
  flutter_hooks: ^0.18.2+1
  netease_music_request: ^1.0.8
  equatable: ^2.0.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
